# --- Application ---
spring.application.name=spring-boot-application-example

# --- Liquibase ---
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/master.xml

# --- H2 prod ---
spring.h2.console.enabled=false

# --- Connection Pool (Hikari) ---
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Error handling (more strict in prod) ---
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
